### ISSUE TITLE
Downloading bwce maven plugin artifacts bundle 

### ISSUE THREAD

**Issue by thirutibco** [TIBCOSoftware/bw6-plugin-maven#322]
Hello,
Is there any way to download the maven artifacts bundle, instead of downloading during the plugin installation process?
We are trying to automate the installation, where we need to refer the downloaded bundle instead of downloading the artifacts from maven as we have some firewall related issues.

Thanks,
Thiru

**Comment by lczupryn** [comment]
needed jars are available in the unpacked config directory.
If it will help you here is a part of my ansible role:

```yaml
- name: "Download TIBCO Maven Plugin v{{install_tib_maven_version}}"
  get_url:
    url: "https://github.com/TIBCOSoftware/bw6-plugin-maven/releases/download/v{{install_tib_maven_version}}/TIB_BW_Maven_Plugin_{{install_tib_maven_version}}.zip"
    dest: "{{tibco_home}}/bwce-{{tibco_bwce_version}}"
  become:  true
  become_user: "{{tibco_user}}"
- name: Extract TIBCO Maven Plugin
  file:
    state: "directory"
    path: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/tib_bw_maveb_plugin"
    owner: "{{tibco_user}}"
    group: "{{tibco_group}}"
  become_user: "{{tibco_user}}"
  become: yes
- unarchive:
    src: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/TIB_BW_Maven_Plugin_{{install_tib_maven_version}}.zip"
    dest: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/tib_bw_maveb_plugin"
    remote_src: yes
    group: "{{tibco_group}}"
    owner: "{{tibco_user}}"
  become_user: "{{tibco_user}}"
  become: yes
- name: Extract bw6-maven-plugin.zip
  file:
    state: "directory"
    path: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/bw6-maven-plugin"
    owner: "{{tibco_user}}"
    group: "{{tibco_group}}"
  become_user: "{{tibco_user}}"
  become: yes
- unarchive:
    src: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/tib_bw_maveb_plugin/config/bw6-maven-plugin.zip"
    dest: "{{tibco_home}}/bwce-{{tibco_bwce_version}}/bw6-maven-plugin"
    remote_src: yes
    group: "{{tibco_group}}"
    owner: "{{tibco_user}}"
  become_user: "{{tibco_user}}"
  become: yes
```
